# Rename this file to languages.toml to enable multilingual support
[ja]
languageName = "日本語"
languagedirection = "ltr"
title = "Koucha"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "Koucha"
weight = 2